import os
import json
import subprocess
from pathlib import Path

LOG_DIR = Path("/Volumes/Rachna-HD/Experiment3Results/logs")
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOG_EXEC_DIR = Path("/Volumes/Rachna-HD/Experiment3Results/logs/executionPhase")
LOG_EXEC_DIR.mkdir(parents=True, exist_ok=True)

LOG_BREAKING_DIR = Path("/Volumes/Rachna-HD/Experiment3Results/logs/breakingPhase")
LOG_BREAKING_DIR.mkdir(parents=True, exist_ok=True)

LOG_CANARY_DIR = Path("/Volumes/Rachna-HD/CanaryResults/logs")
LOG_CANARY_DIR.mkdir(parents=True, exist_ok=True)


LOG_CANARY_V2_DIR = Path("/Volumes/Rachna-HD/CanaryResults/logsv2")
LOG_CANARY_V2_DIR.mkdir(parents=True, exist_ok=True)
class DockerRunError(Exception):
    def __init__(self, message, log_path):
        super().__init__(message)
        self.log_path = log_path


class MavenTestError(Exception):
    def __init__(self, message, log_path):
        super().__init__(message)
        self.log_path = log_path


def get_last_lines(log_content, num_lines=50):
    lines = log_content.strip().splitlines()
    return '\n'.join(lines[-num_lines:]).strip()

# Might improve this code as per now, it is hardcoded for types of errors.
def classify_compilation_error(log_content):
    log_lower = log_content.lower()

    if "lambda expressions are not supported in" in log_lower:
        return {
            "type": "syntax error",
            "subtype": "java version incompatibility",
            "content": "LLM-generated code uses Java 8+ features (e.g., lambdas), but the target project compiles with -source 1.7"
        }
    elif "illegal character: '`'" in log_lower:
        return {
            "type": "syntax error",
            "subtype": "invalid character",
            "content": "Backticks (`) are not valid in Java. Possibly introduced by LLM formatting."
        }
    elif "cannot find symbol" in log_lower or "symbol:   class" in log_lower:
        return {
            "type": "dependency error",
            "content": "Missing or unrecognized classes; possibly a dependency issue."
        }
    elif " ';' expected" in log_lower or "illegal start of type" in log_lower:
        return {
            "type": "syntax error",
            "content": "Likely syntax issue in the Java code."
        }
    else:
        return {
            "type": "unknown",
            "content": get_last_lines(log_content, 10)
        }

# This is an utility function to clean the code generated by LLM , just to remove the extra text and symbols.
def clean_llm_code(lines):
    cleaned = []
    for line in lines:
        if line.strip().startswith("```"):
            continue
        line = line.replace("`", "")
        line = line.replace("’", "'").replace("‘", "'")
        line = line.replace("“", "\"").replace("”", "\"")
        cleaned.append(line)
    return cleaned

# I have already extracted the package and test class root path from docker image for each BBC, it is stored in a file named package_structure_summary.txt. This function 
# is just acting as a lookup to the txt file to extract the text class path. It returns the Test root and the package path details.
def parse_package_summary(path):
    info = {}
    current_id = current_type = None
    test_root = package = None

    with open(path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("===="):
                parts = line.split(" | ")
                if len(parts) >= 2:
                    current_id = parts[0].replace("====", "").strip()
                    current_type = parts[1].strip()
                    test_root = package = None
            elif line.startswith("Test root:"):
                test_root = line.split("Test root:")[1].strip()
            elif line.startswith("package:"):
                package = line.split("package:")[1].strip()

            if current_id and current_type and test_root and package:
                info[(current_id, current_type)] = (test_root, package)
                current_id = current_type = test_root = package = None
    return info
